---
- name: win10_baseline.yml
  hosts: windows
  tasks:

    - name: Installing Chocolatey packages
      win_chocolatey:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ app_data }}"

    - name: Enable autologin
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: AutoAdminLogon
        data: 1
        type: string

    - name: Enable autologin Password
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DefaultPassword
        data: runner
        type: string
