---
- name: win10_registry.yml
  hosts: windows
  tasks:

    - name: Disable autologin
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: AutoAdminLogon
        data: 0
        type: string

    - name: Enable Remote Desktop
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword
