---
- name: win10_baseline.yml
  hosts: windows
  tasks:

    - name: Installing Chocolatey packages
      win_chocolatey:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ app_data }}"
