---
- name: win2016std.yml
  hosts: windows
  tasks:

    - name: Installing Chocolatey packages
      win_chocolatey:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        state: present
      with_items:
        - { name: 'vcredist2008' }
        - { name: 'vcredist2010' }
        - { name: 'vcredist2012' }
        - { name: 'vcredist2013' }
        - { name: 'vcredist2017' }
        - { name: 'dotnet3.5' }
        - { name: 'dotnet4.7.1' }
        - { name: 'vmware-tools', version: '10.1.15.6677369' }

    - name: Disable autologin
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: AutoAdminLogon
        data: 0
        type: string

    - name: Enable Remote Desktop
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword
