---
- name: win2016std.yml
  hosts: windows
  tasks:

    - name: Installing Chocolatey packages
      win_chocolatey:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        state: present
      with_items:
        - { name: 'notepadplusplus.install', version: '7.3' }
        - { name: 'googlechrome', version: '62.0.3202.62' }
        - { name: '7zip.install', version: '16.4.0.20170506' }
        - { name: 'vmware-horizon-client', version: '4.4.0' }
        - { name: 'vmware-tools', version: '10.1.15.6677369' }

    - name: Disable autologin
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: AutoAdminLogon
        data: 0
        type: string
